# Based on https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --extra docs --frozen
    - uv run -m sphinx -T -b html -d docs/build/doctrees -D language=en docs/source $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/source/conf.py
